name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  buildAndTest:
    uses: ./.github/workflows/buildAndTest.yaml

  release:
    needs: buildAndTest
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: buildAndTest
    name: Build Docker Container
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "fleaz"
          password: ${{ secrets.PAT }}
      - name: Push to GH Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fleaz/cpthook:stable
